---
output: github_document
---

# Academic CV

Clone of [Joseph Casillas' CV template](https://github.com/jvcasillas/cv).

Last update: `r Sys.Date()`

## Overview

Version controlled CV using the `moderncv` LaTeX class. 
Ported to RMarkdown. 

## Notes

- Occasionally it is necessary to reinstall the fonts used in this repo (after a system update, for example)
- They live in `assets/fonts` and should only need to be installed once

## To add:

- Research
  - Publications
    - published: 
    - in press: 
    - under review: 
    - accepted:
    - in prep: 
    - Misc:
  - Presentations
    - Create a personal website workshop
    - Bridgwater-Raritan high school on bilingualism for parents
    - Mexican consulate presentations
      - continuing education
- Teaching
- Service
  - chair sessions
  - Reviews
  - Committees
    Language at Crossroads planning committee
  - Mentoring
    Mesas de español
- Academic accolades
  - Middlebury Portuguese teacher fellowship
- Software
- Misc
  - stats contractor for kristen and nuria
  - GSA treasurer
  - CHS science fair
